### ISSUE TITLE
Can't print uint32_t. Overflows.

### ISSUE THREAD

**Issue by dragospuri** [Chris--A/PrintEx#7]
Example

  uint32_t a=65537;
  myLCD.printf("%06d", a);

Gives
000001

**Comment by Chris--A** [comment]
Hi, you need to specify the length parameter otherwise it uses 16 bit data. I'll update the docs to say default 16 bits, maximum 32 bits.


```Arduino
uint32_t a=65537;
myLCD.printf("%06ld", a);
```

It will output `065537`.
